hello world

diff --git a/14-logs b/14-logs
--- a/14-logs
+++ b/14-logs
@@ -1,66 +1,46 @@
-#!/bin/bash
+#!/bin/bash 
 
-USERID=$(id -u)
-R=\e[31m
-G=\e32m
-Y=\e[33m
-N=\e[0m
+# this script is created to install multiple applications at once in a server and it will store the logs of each step 
 
-LOG_FOLDER="/var/log/shell-scripts"
-SCRIPT_NAME="$0"
-LOG_FILE="$LOG_FOLDER/$SCRIPT_NAME.log"
+USERID=$(ID -U)
+USERNAME=$USER
 
-mkdir -p /var/log/shell-scripts
+LOGS_FOLDER="/var/log/shell_logs"
+SCRIPT_NAME=$(basename $0)
+LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME.LOG"
 
-VALIDATE(){
-    if [ $1 -eq 0 ]
-    then 
-        echo " $1 successfully installed in yuor server"
-    else
-        echo " $1 installation failed in your server"  
-    }
-    
+mkdir -p $LOGS_FOLDER
+
 if [ $USERID -eq 0 ]
+
    then 
-        echo " you have root privlages"
+    echo " $USERNAME has root privlages " &>> $LOG_FILE
+    else  
+    echo " error:: $USERNAME don't have root privlages " &>> $LOG_FILE
+    exit 1
+fi 
+
+VALIDATE() {
+    if [ $@ -eq 0 ]
+    then 
+        echo " successfully installed $@ "
+    else 
+        echo " error:: failed to install $@ "
+    fi
+}
+
+dnf list installed $@ &>> $LOG_FILE
+ 
+  if [ $? -ne 0 ]
+    then 
+        echo " $@ is not installed, installing now..." &>> $LOG_FILE
+        
+        dnf install $@ -y
+        VALIDATE $? "$@"
     else
-        echo "error :: you don't have root user privlages" 
-    exit 1   
+        echo "$@ is already isntalled in server nothing to do .." &>> $LOG_FILE
+        exit 1
+    
+  fi 
 
-fi   
 
-dnf list installed httpd &>> $LOG_FILE
-if [ $? -ne 0 ]
-
-then 
-    echo "httpd installed in your server "
-
-    dnf install httpd -y &>> $LOG_FILE
-    $VALIDATE $? "httpd"
-else 
-    echo "httpd is already installed in your server nothing to do"
-fi
-
-dnf list installed nginx &>> $LOG_FILE
-if [ $? -ne 0 ]
-
-then 
-    echo "nginx installed in your server "
-
-    dnf install nginx -y &>> $LOG_FILE
-    $VALIDATE $? "nginx"
-else 
-    echo "nginx is already installed in your server nothing to do"
-fi
-
-dnf list installed python3 &>> $LOG_FILE
-if [ $? -ne 0 ]
-
-then 
-    echo "python3 installed in your server "
-
-    dnf install python3 -y &>> $LOG_FILE
-    $VALIDATE $? "python3"
-else 
-    echo "python3 is already installed in your server nothing to do" &>> $LOG_FILE
-fi
