hello world

diff --git a/14-logs b/14-logs
--- a/14-logs
+++ b/14-logs
@@ -22,11 +22,11 @@ else
 fi 
 
 VALIDATE() {
-    if [ $@ -eq 0 ]
+    if [ $1 -eq 0 ]
     then 
-        echo " successfully installed $@ "
+        echo " successfully installed $1 "
     else 
-        echo " error:: failed to install $@ "
+        echo " error:: failed to install $1 "
     fi
 }
 
@@ -36,10 +36,10 @@ dnf list installed $@ &>> $LOG_FILE
     then 
         echo " $@ is not installed, installing now..." | tee -a $LOG_FILE
         
-        dnf install $@ -y
-        VALIDATE $? "$@"
+        dnf install $1 -y
+        $VALIDATE $? "$1"
     else
-        echo "$@ is already isntalled in server nothing to do .." | tee -a $LOG_FILE
+        echo "$1 is already isntalled in server nothing to do .." | tee -a $LOG_FILE
         exit 1
     
   fi 
